name: Security Audit

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pip-audit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt -f cyclonedx-json -o pip-audit.cdx.json || true

      - name: Upload audit SARIF (optional conversion)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-cyclonedx
          path: pip-audit.cdx.json
